## spring.application.name=backendpropio
server:
  port: 8081
  error:
    include-message: always


spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a base de datos--info de herok
  datasource:
    url: jdbc:postgresql://S7P6contptgpropio:5432/S7P6bddPropio?socketTimeout=3
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver